# Indexing and Slicing

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  
print(arr[-1]) 

10
40


In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  
print(arr[:3])   
print(arr[::2])  

[20 30 40]
[10 20 30]
[10 30 50]


In [3]:
#Create a 3×3 array filled with random numbers and print its shape.
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
#Reshape a 1D array of size 9 into a 3×3 matrix.


arr=np.array([[2,4,3],[4,6,8],[4,4,4]], dtype=np.float32)

In [4]:
arr

array([[2., 4., 3.],
       [4., 6., 8.],
       [4., 4., 4.]], dtype=float32)

In [5]:
arr.shape
# Change the DataType
arr.astype(np.int32)

array([[2, 4, 3],
       [4, 6, 8],
       [4, 4, 4]], dtype=int32)

In [6]:
arr2=[1, 2, 3, 4, 5, 6]

In [7]:
arr2

[1, 2, 3, 4, 5, 6]

In [8]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
print(arr2[1::2])

[2, 4, 6]


In [9]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr3=np.array([1,2,3,4,5,6,7,8,9])
print(arr3)
arr3.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [10]:
n1=arr3[:3]
n2=arr3[3:6]
n3=arr3[6:9]
print(n1,n2,n3)


[1 2 3] [4 5 6] [7 8 9]


In [11]:
arr4=np.array([n1,n2,n3])

In [12]:
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
